fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_registration_confirm_override:
    pattern: /register/confirm/{token}
    defaults:
        _controller: DtdbBuilderBundle:Registration:confirm

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

alsciende_user:
    resource: "@DtdbBuilderBundle/Resources/config/routing.yml"
    prefix:   /

alsciende_builder:
    resource: "@DtdbBuilderBundle/Resources/config/routing.yml"
    prefix:   /

alsciende_cards:
    resource: "@DtdbBuilderBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: DtdbBuilderBundle:Security:login }

oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: DtdbBuilderBundle:Security:loginCheck }
