deck_builder_index:
    pattern: /{_locale}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Index:index
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_buildform:
    pattern:  /{_locale}/deck/new
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:buildform
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_initbuild:
    pattern: /{_locale}/deck/build/{card_code}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:initbuild
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_save:
    pattern: /{_locale}/deck/save
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:save
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_edit:
    pattern: /{_locale}/deck/edit/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:edit
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        deck_id: \d+

deck_view:
    pattern: /{_locale}/deck/view/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:view
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        deck_id: \d+

deck_duplicate:
    pattern: /{_locale}/deck/duplicate/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:duplicate
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        deck_id: \d+

decks_list:
    pattern: /{_locale}/decks
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:list
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_publish:
    pattern: /deck/can_publish/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:publish
        deck_id: \d+

deck_autosave:
    pattern: /deck/autosave/{deck_id}
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:autosave

deck_delete:
    pattern: /{_locale}/deck/delete
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:delete
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_delete_list:
    pattern: /{_locale}/deck/delete_list
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:deleteList
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_import:
    pattern: /{_locale}/deck/import
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:import
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_textimport:
    pattern: /{_locale}/deck/textimport
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:textimport
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

deck_fileimport:
    pattern: /{_locale}/deck/fileimport
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:fileimport
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

decks_download_all:
    pattern: /deck/export/all
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:downloadall

decks_upload_all:
    pattern: /deck/import/all
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:uploadall

deck_export_octgn:
    pattern: /deck/export/octgn/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:octgnexport
    requirements:
        deck_id: \d+

deck_export_text:
    pattern: /deck/export/text/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:textexport
    requirements:
        deck_id: \d+

deck_export_octgn_list:
    pattern: /deck/export/octgn/list
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:octgnexportList

deck_export_text_list:
    pattern: /deck/export/text/list
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:textexportList

deck_email:
    pattern: /deck/export/email/{deck_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Builder:email
        deck_id: \d+

deck_copy:
    pattern: /{_locale}/deck/copy/{decklist_id}
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Builder:copy
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        decklist_id: \d+

decklist_export_octgn:
    pattern: /decklist/export/octgn/{decklist_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:octgnexport
    requirements:
        decklist_id: \d+

decklist_export_text:
    pattern: /decklist/export/text/{decklist_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:textexport
    requirements:
        decklist_id: \d+

decklist_new:
    pattern: /{_locale}/deck/publish
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Social:new
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl


decklists_searchform:
    pattern: /{_locale}/decklists/search
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:search
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

decklists_list:
    pattern: /{_locale}/decklists/{type}/{page}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:list
        page: 1
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        page: \d+

decklist_detail:
    pattern: /{_locale}/decklist/{decklist_id}/{decklist_name}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:view
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        decklist_id: \d+

decklist_favorite:
    pattern: /user/favorite
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Social:favorite

decklist_like:
    pattern: /user/like
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Social:vote

decklist_comment:
    pattern: /user/comment
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Social:comment

decklist_edit:
    pattern: /decklist/edit/{decklist_id}
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Social:edit
    requirements:
        decklist_id: \d+

decklist_delete:
    pattern: /decklist/delete/{decklist_id}
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Social:delete
    requirements:
        decklist_id: \d+

decklists_diff:
    pattern: /{_locale}/decklists/diff/{decklist1_id}/{decklist2_id}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Diff:decklistDiff
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        decklist1_id: \d+
        decklist2_id: \d+

user_profile:
    pattern: /{_locale}/user/profile
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Default:profile
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

user_profile_save:
    pattern: /{_locale}/user/profile_save
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Default:saveProfile
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

user_profile_view:
    pattern: /{_locale}/profile/{user_id}/{user_name}/{page}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:profile
        page: 1
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        user_id: \d+

user_comments:
    pattern: /{_locale}/user/comments/{page}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:usercomments
        page: 1
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

all_comments:
    pattern: /{_locale}/deckcomments/{page}
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:comments
        _locale: en
        page: 1
    requirements:
        _locale: en|fr|de|es|it|pl

donators:
    pattern: /{_locale}/donators
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Social:donators
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl


tools_demo:
    pattern: /tools/demo
    methods: [GET]
    defaults:
        _controller: DtdbBuilderBundle:Tools:demo


api_decklist:
    pattern: /api/decklist/{decklist_id}.{_format}
    defaults:
        _controller: DtdbBuilderBundle:Api:decklist
        _format: json
    requirements:
        _format: json
        decklist_id: \d+

api_decklists:
    pattern: /api/decklists/by_date/{date}.{_format}
    defaults:
        _controller: DtdbBuilderBundle:Api:decklists
        _format: json
    requirements:
        _format: json
        date: \d\d\d\d-\d\d-\d\d

api_decks:
    pattern: /api/decks
    defaults:
        _controller: DtdbBuilderBundle:Api:decks

api_oauth2_decks:
    pattern: /api_oauth2/decks
    defaults:
        _controller: DtdbBuilderBundle:Api:decks

api_oauth2_save_deck:
    pattern: /api_oauth2/save_deck/{deck_id}
    defaults:
        _controller: DtdbBuilderBundle:Api:saveDeck
    requirements:
        deck_id: \d+

api_oauth2_publish_deck:
    pattern: /api_oauth2/publish_deck/{deck_id}
    defaults:
        _controller: DtdbBuilderBundle:Api:publish
    requirements:
        deck_id: \d+

tag_add:
    pattern: /tag/add
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Tag:add

tag_remove:
    pattern: /tag/remove
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Tag:remove

tag_clear:
    pattern: /tag/clear
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Tag:clear

user_info:
    pattern: /user/info
    defaults: { _controller: DtdbBuilderBundle:Default:info }

card_review_post:
    pattern: /review/post
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Review:post

card_review_edit:
    pattern: /review/edit
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Review:edit

card_review_like:
    pattern: /review/like
    methods: [POST]
    defaults:
        _controller: DtdbBuilderBundle:Review:like

card_review_remove:
    pattern: /review/remove/{id}
    defaults:
        _controller: DtdbBuilderBundle:Review:remove

card_reviews_list:
    pattern: /{_locale}/reviews/{page}
    defaults:
        _controller: DtdbBuilderBundle:Review:list
        _locale: en
        page: 1
    requirements:
        _locale: en|fr|de|es|it|pl
        page: \d+

dtdb_cards_admin_suit:
    resource: "@DtdbBuilderBundle/Resources/config/routing/suit.yml"
    prefix:   /admin/suit

dtdb_cards_admin_gang:
    resource: "@DtdbBuilderBundle/Resources/config/routing/gang.yml"
    prefix:   /admin/gang

dtdb_cards_admin_shooter:
    resource: "@DtdbBuilderBundle/Resources/config/routing/shooter.yml"
    prefix:   /admin/shooter

dtdb_cards_admin_type:
    resource: "@DtdbBuilderBundle/Resources/config/routing/type.yml"
    prefix:   /admin/type

dtdb_cards_admin_card:
    resource: "@DtdbBuilderBundle/Resources/config/routing/card.yml"
    prefix:   /admin/card

DtdbBuilderBundle_admin_cycle:
    resource: "@DtdbBuilderBundle/Resources/config/routing/cycle.yml"
    prefix:   /admin/cycle

DtdbBuilderBundle_admin_pack:
    resource: "@DtdbBuilderBundle/Resources/config/routing/pack.yml"
    prefix:   /admin/pack

DtdbBuilderBundle_admin_card:
    resource: "@DtdbBuilderBundle/Resources/config/routing/card.yml"
    prefix:   /admin/card

cards_list:
    pattern:  /{_locale}/set/{pack_code}/{view}/{sort}/{page}
    defaults:
        _controller: DtdbBuilderBundle:Search:list
        _locale: en
        view: list
        sort: set
        page: 1
    requirements:
        _locale: en|fr|de|es|it|pl
        page: \d+

cards_zoom:
    pattern:  /{_locale}/card/{card_code}
    defaults:
        _controller: DtdbBuilderBundle:Search:zoom
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        card_code: \d+

cards_cycle:
    pattern:  /{_locale}/cycle/{cycle_code}/{view}/{sort}
    defaults:
        _controller: DtdbBuilderBundle:Search:cycle
        _locale: en
        view: list
        sort: gang
    requirements:
        _locale: en|fr|de|es|it|pl

cards_search:
    pattern:  /{_locale}/search
    defaults:
        _controller: DtdbBuilderBundle:Default:search
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_find:
    pattern:  /find/
    defaults:
        _controller: DtdbBuilderBundle:Search:find

cards_processSearchForm:
    pattern:  /process/
    defaults:
        _controller: DtdbBuilderBundle:Search:process

cards_about:
    pattern:  /{_locale}/about
    defaults:
        _controller: DtdbBuilderBundle:Default:about
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_changelog:
    pattern:  /{_locale}/changelog
    defaults:
        _controller: DtdbBuilderBundle:Default:changelog
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_rules:
    pattern:  /{_locale}/rules
    defaults:
        _controller: DtdbBuilderBundle:Default:rules
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_extraRules:
    pattern:  /{_locale}/extraRules
    defaults:
        _controller: DtdbBuilderBundle:Default:extraRules
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_collectedRulings:
    pattern:  /{_locale}/collectedRulings
    defaults:
        _controller: DtdbBuilderBundle:Default:collectedRulings
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_structure:
    pattern:  /{_locale}/structure
    defaults:
        _controller: DtdbBuilderBundle:Default:structure
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_faq:
    pattern:  /{_locale}/faq
    defaults:
        _controller: DtdbBuilderBundle:Default:faq
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_floor:
    pattern:  /{_locale}/floorRules
    defaults:
        _controller: DtdbBuilderBundle:Default:floorRules
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_octgnGuide:
    pattern:  /{_locale}/octgnGuide
    defaults:
        _controller: DtdbBuilderBundle:Default:octgnGuide
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_oldRules:
    pattern:  /{_locale}/oldRules
    defaults:
        _controller: DtdbBuilderBundle:Default:oldRules
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_oldFaqs:
    pattern:  /{_locale}/oldFaqs
    defaults:
        _controller: DtdbBuilderBundle:Default:oldFaqs
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

cards_api:
    pattern:  /{_locale}/apidoc
    defaults:
        _controller: DtdbBuilderBundle:Default:apidoc
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

api_cards:
    pattern: /api/cards/
    defaults:
        _controller: DtdbBuilderBundle:Api:cards

api_card:
    pattern: /api/card/{card_code}.{_format}
    defaults:
        _controller: DtdbBuilderBundle:Api:card
        _format: json
    requirements:
        _format: json
        card_code: \d+

api_sets:
    pattern: /api/sets/
    defaults:
        _controller: DtdbBuilderBundle:Api:sets

api_set:
    pattern: /api/set/{pack_code}.{_format}
    defaults:
        _controller: DtdbBuilderBundle:Api:set
        _format: json
    requirements:
        _format: json|xml|xlsx

DtdbBuilderBundle_admin_cards:
    resource: "@DtdbBuilderBundle/Resources/config/routing/cards.yml"
    prefix:   /admin/cards

DtdbBuilderBundle_admin_rulings:
    resource: "@DtdbBuilderBundle/Resources/config/routing/rulings.yml"
    prefix:   /admin/rulings

DtdbBuilderBundle_admin_rxc:
    resource: "@DtdbBuilderBundle/Resources/config/routing/rxc.yml"
    prefix:   /admin/rxc

excel_form:
    pattern: /admin/excel/form
    defaults:
        _controller: DtdbBuilderBundle:Excel:form

excel_upload:
    pattern: /admin/excel/upload
    defaults:
        _controller: DtdbBuilderBundle:Excel:upload

excel_confirm:
    pattern: /admin/excel/confirm
    defaults:
        _controller: DtdbBuilderBundle:Excel:confirm
